### ISSUE TITLE
feature request: "is tomorrow" sensors

### ISSUE THREAD

**Issue by DavidDeSloovere** [olibos/HomeAssistant-RecycleApp#23]
First and foremost: thanks for taking the time to create this integration.

I just installed it and works without issues.
On my dashboad, I would like to add sensor if collection is tomorrow.
I know I can check the days attribute, tested in Developer > Templates and that'll work fine.

A great addition to help everyone using this would be extra sensors if collection is 'tomorrow' (and maybe also for 'today' is someone want to trigger on the day itself). I know it can be done with template sensor. When I have these I can add them to the readme if you prefer that.

**Comment by olibos** [comment]
Hello @DavidDeSloovere ,

Thank you for your kind words!

For the tomorrow sensor, someone has already request that kind of sensor in #16.

I'm not really convinced of the utility over a simple template sensor.

If you have those sensor what kind of data would you want to have in those?

**Comment by olibos** [comment]
Hello @DavidDeSloovere ,

I haven't heard back from you in a while, and this issue has been inactive for quite some time. As a result, I am going to assume that it has been resolved or is no longer relevant, and I will be closing this issue.

If you feel this issue is still relevant, please feel free to reopen it, and I'll be happy to take another look. Alternatively, if you have any further questions or concerns, please don't hesitate to reach out to me.
