### ISSUE TITLE
Refresh Interval

### ISSUE THREAD

**Issue by yannickdm** [olibos/HomeAssistant-RecycleApp#81]
Hey, what is the refresh intervan on Hass for the days ? I was checking some stuff at around 10 AM, while PMD sensor should have been 0 days; but it was 1 day. Is there a way to tweak this a bit ?

Thanks!
Yannick

**Comment by olibos** [comment]
Hello @yannickdm ,

Normally it's refreshed at midnight just after the sync with Fostplus API.

Can you check in log if there was an issue during last sync? 

Sometimes there is an API maintenance or a connectivity issue which may affect the days update.

There is a pending enhancement to avoid that #80. 

Thanks for your feedback.

**Comment by dirkvankeer** [comment]
I had the same problem yesterday 05/11/24.  Although the due date  for GFT was 06/11/2024, the attribute 'days' said "3".  So my automation based on the attribute 'days' did not trigger.
This morning 5:14 06/11/2024 the attribute 'days' sais "0", so that is correct.
Possible to look into this.
Many thanx.

**Comment by yannickdm** [comment]
+1 for me again, not for this particular incidend, but I have noticed that it re-occurs almost every time.  My bins have stayed on the drive-way for a long time, oops.

**Comment by olibos** [comment]
While I haven't been able to investigate this thoroughly yet, I plan to address this in a beta release scheduled for next week. I'll prioritize reviewing the refresh timing logic.

I'll update this issue once I have more concrete information to share. Thanks for your patience.

**Comment by olibos** [comment]
Do you have any log warning or error arround midnight?

**Comment by dirkvankeer** [comment]
Not that I know off...

**Comment by MarshallRDC** [comment]
Same issue here

**Comment by MarshallRDC** [comment]
> 🎉 A new beta version is now available: [v2.6.0-b1](https://github.com/olibos/HomeAssistant-RecycleApp/releases/tag/v2.6.0-b1).
> 
> Could you give it a try and let me know if it resolves the issue?

It seems to be fixed, I don't have the error in my logs anymore and the days attribute seems to be correct now as well. In 4 days I have a collection so curious if my notification triggers now but am pretty sure it will.

**Comment by olibos** [comment]
Thank you for your feedback! I'm glad to hear the issue seems to be resolved. Please note that if the API doesn't respond to Home Assistant, the error message will now be more specific, changing from "Unexpected error fetching RecycleAppGetRecyclingParks data" to "Error fetching RecycleAppGetRecyclingParks data:". The integration will retry automatically in case of failure.

Let me know how things go with your next collection!

**Comment by MarshallRDC** [comment]
> Thank you for your feedback! I'm glad to hear the issue seems to be resolved. Please note that if the API doesn't respond to Home Assistant, the error message will now be more specific, changing from "Unexpected error fetching RecycleAppGetRecyclingParks data" to "Error fetching RecycleAppGetRecyclingParks data:". The integration will retry automatically in case of failure.
> 
> Let me know how things go with your next collection!

Tomorrow is the next collection and my automation triggered as expected. Thanks for your prompt action on this topic! Highly appreciated. 👌
