### ISSUE TITLE
Huisvuil entity no longer available (3150)

### ISSUE THREAD

**Issue by jeroendw88** [olibos/HomeAssistant-RecycleApp#88]
Since a couple days, I no longer have the huisvuil entity.
It only loads the pmd,  papier-karton and gft entity. Postcode 3150. Anyone else had noticed?

**Comment by olibos** [comment]
Hello @jeroendw88,

Have you checked on https://recycleapp.be/ to see if the information is still available?
If it is, could you please provide a nearby address so I can look into it further?

Thanks,
Olivier

**Comment by olibos** [comment]
Hi @jeroendw88,  

Thank you for reporting back.  

The issue was related to the "container" collection type, which wasn’t supported in the integration.
That has now been fixed, as shown below:  
![image](https://github.com/user-attachments/assets/c0b07a5a-9058-402f-95b6-f02684c48218)  

Could you try the latest beta version ([v2.6.0-b2](https://github.com/olibos/HomeAssistant-RecycleApp/releases/tag/v2.6.0-b2)) and let me know if it resolves the issue?  

Olivier

**Comment by jeroendw88** [comment]
Hi @olibos,

The beta works! Thanks a lot!! 😉🙏
